spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:adm_catalog_database_test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: root
    password: root
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    h2:
    console:
      enabled: true
      path: /h2

    spring:
      jpa:
