spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:adm_catalog_database_test;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: root
    password: root
  h2:
    console:
      enabled: true
      path: /h2