mysql:
  username: root
  password: root
  schema: adm_catalog_db
  url: localhost:${mysql.port}

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration