version: '3.7'

services:
  mysql:
    container_name: adm_catalog_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=adm_catalog_db
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      - adm_catalog_network

  rabbitmq:
    container_name: adm_catalog_rabbitmq
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: adm_catalog
      RABBITMQ_DEFAULT_PASS: 123456
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - adm_catalog_network

networks:
  adm_catalog_network:
